// Generated by CoffeeScript 1.9.3
(function() {
  var app;

  app = angular.module('smarkingApp', []);

  app.controller('smarkingCtrl', function($scope) {
    $scope.data = [[300, 400, 300], [250, 300, 250]];
  });

  app.directive('bars', function($parse) {
    return {
      restrict: 'E',
      replace: true,
      template: '<div id="chart"></div>',
      link: function(scope, element, attrs) {
        var chart, data;
        data = attrs.data.split(',');
        chart = d3.select('#chart').append('div').attr('class', 'chart').selectAll('div').data(data).enter().append('div').transition().ease('elastic').style('width', function(d) {
          return d + '%';
        }).text(function(d) {
          return d + '%';
        });
      }
    };
  });

}).call(this);
